version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    versioning-strategy: 'increase'
    target-branch: 'master'
    labels:
      - 'npm dependencies'
