import { Blizzard } from '../../core'
import * as classic from '../../resources/classic'
import * as wow from '../../resources/wow'

export class WoWClassic extends Blizzard {
  accountCharacterProfile = this.createClientResourceRequest(wow.accountCharacterProfile.bind(this, 'profile-classic'))
  accountProfile = this.createClientResourceRequest(wow.accountProfile.bind(this, 'profile-classic'))
  auctionHouse = this.createClientResourceRequest(classic.auctionHouse.bind(this, 'dynamic-classic'))
  characterAchievements = this.createClientResourceRequest(wow.characterAchievements.bind(this, 'profile-classic'))
  characterAppearance = this.createClientResourceRequest(wow.characterAppearance.bind(this, 'profile-classic'))
  characterEquipment = this.createClientResourceRequest(wow.characterEquipment.bind(this, 'profile-classic'))
  characterHunterPets = this.createClientResourceRequest(wow.characterHunterPets.bind(this, 'profile-classic'))
  characterMedia = this.createClientResourceRequest(wow.characterMedia.bind(this, 'profile-classic'))
  characterPVP = this.createClientResourceRequest(wow.characterPVP.bind(this, 'profile-classic'))
  characterProfile = this.createClientResourceRequest(wow.characterProfile.bind(this, 'profile-classic'))
  characterStatistics = this.createClientResourceRequest(wow.characterStatistics.bind(this, 'profile-classic'))
  connectedRealm = this.createClientResourceRequest(wow.connectedRealm.bind(this, 'dynamic-classic'))
  connectedRealmSearch = this.createClientResourceRequest(wow.connectedRealmSearch.bind(this, 'dynamic-classic'))
  creature = this.createClientResourceRequest(wow.creature.bind(this, 'static-classic'))
  creatureFamily = this.createClientResourceRequest(wow.creatureFamily.bind(this, 'static-classic'))
  creatureSearch = this.createClientResourceRequest(wow.creatureSearch.bind(this, 'static-classic'))
  creatureType = this.createClientResourceRequest(wow.creatureType.bind(this, 'static-classic'))
  guild = this.createClientResourceRequest(wow.guild.bind(this, 'profile-classic'))
  guildCrest = this.createClientResourceRequest(wow.guildCrest.bind(this, 'static-classic'))
  item = this.createClientResourceRequest(wow.item.bind(this, 'static-classic'))
  itemSearch = this.createClientResourceRequest(wow.itemSearch.bind(this, 'static-classic'))
  mediaSearch = this.createClientResourceRequest(wow.mediaSearch.bind(this, 'static-classic'))
  playableClass = this.createClientResourceRequest(wow.playableClass.bind(this, 'static-classic'))
  playableRace = this.createClientResourceRequest(wow.playableRace.bind(this, 'static-classic'))
  powerType = this.createClientResourceRequest(wow.powerType.bind(this, 'static-classic'))
  realm = this.createClientResourceRequest(wow.realm.bind(this, 'dynamic-classic'))
  realmSearch = this.createClientResourceRequest(wow.realmSearch.bind(this, 'dynamic-classic'))
  region = this.createClientResourceRequest(wow.region.bind(this, 'dynamic-classic'))
  token = this.createClientResourceRequest(wow.token.bind(this, 'dynamic-classic'))
}

export class WoWClassicEra extends Blizzard {
  accountCharacterProfile = this.createClientResourceRequest(
    wow.accountCharacterProfile.bind(this, 'profile-classic1x'),
  )
  accountProfile = this.createClientResourceRequest(wow.accountProfile.bind(this, 'profile-classic1x'))
  auctionHouse = this.createClientResourceRequest(classic.auctionHouse.bind(this, 'dynamic-classic'))
  characterAchievements = this.createClientResourceRequest(wow.characterAchievements.bind(this, 'profile-classic1x'))
  characterAppearance = this.createClientResourceRequest(wow.characterAppearance.bind(this, 'profile-classic1x'))
  characterEquipment = this.createClientResourceRequest(wow.characterEquipment.bind(this, 'profile-classic1x'))
  characterHunterPets = this.createClientResourceRequest(wow.characterHunterPets.bind(this, 'profile-classic1x'))
  characterMedia = this.createClientResourceRequest(wow.characterMedia.bind(this, 'profile-classic1x'))
  characterPVP = this.createClientResourceRequest(wow.characterPVP.bind(this, 'profile-classic1x'))
  characterProfile = this.createClientResourceRequest(wow.characterProfile.bind(this, 'profile-classic1x'))
  characterStatistics = this.createClientResourceRequest(wow.characterStatistics.bind(this, 'profile-classic1x'))
  connectedRealm = this.createClientResourceRequest(wow.connectedRealm.bind(this, 'dynamic-classic1x'))
  connectedRealmSearch = this.createClientResourceRequest(wow.connectedRealmSearch.bind(this, 'dynamic-classic1x'))
  creature = this.createClientResourceRequest(wow.creature.bind(this, 'static-classic1x'))
  creatureFamily = this.createClientResourceRequest(wow.creatureFamily.bind(this, 'static-classic1x'))
  creatureSearch = this.createClientResourceRequest(wow.creatureSearch.bind(this, 'static-classic1x'))
  creatureType = this.createClientResourceRequest(wow.creatureType.bind(this, 'static-classic1x'))
  guild = this.createClientResourceRequest(wow.guild.bind(this, 'profile-classic1x'))
  guildCrest = this.createClientResourceRequest(wow.guildCrest.bind(this, 'static-classic1x'))
  item = this.createClientResourceRequest(wow.item.bind(this, 'static-classic1x'))
  itemSearch = this.createClientResourceRequest(wow.itemSearch.bind(this, 'static-classic1x'))
  mediaSearch = this.createClientResourceRequest(wow.mediaSearch.bind(this, 'static-classic1x'))
  playableClass = this.createClientResourceRequest(wow.playableClass.bind(this, 'static-classic1x'))
  playableRace = this.createClientResourceRequest(wow.playableRace.bind(this, 'static-classic1x'))
  powerType = this.createClientResourceRequest(wow.powerType.bind(this, 'static-classic1x'))
  realm = this.createClientResourceRequest(wow.realm.bind(this, 'dynamic-classic1x'))
  realmSearch = this.createClientResourceRequest(wow.realmSearch.bind(this, 'dynamic-classic1x'))
  region = this.createClientResourceRequest(wow.region.bind(this, 'dynamic-classic1x'))
  token = this.createClientResourceRequest(wow.token.bind(this, 'dynamic-classic1x'))
}

export type WoWClassicClient = WoWClassic
