import { Blizzard } from '../../core'
import * as classic from '../../resources/classic'
import * as wow from '../../resources/wow'

export class WoWClassic extends Blizzard {
  accountCharacterProfile = this.createClientResourceRequest(wow.accountCharacterProfile, 'profile-classic')
  accountProfile = this.createClientResourceRequest(wow.accountProfile, 'profile-classic')
  auctionHouse = this.createClientResourceRequest(classic.auctionHouse, 'dynamic-classic')
  characterAchievements = this.createClientResourceRequest(wow.characterAchievements, 'profile-classic')
  characterAppearance = this.createClientResourceRequest(wow.characterAppearance, 'profile-classic')
  characterEquipment = this.createClientResourceRequest(wow.characterEquipment, 'profile-classic')
  characterHunterPets = this.createClientResourceRequest(wow.characterHunterPets, 'profile-classic')
  characterMedia = this.createClientResourceRequest(wow.characterMedia, 'profile-classic')
  characterPVP = this.createClientResourceRequest(wow.characterPVP, 'profile-classic')
  characterProfile = this.createClientResourceRequest(wow.characterProfile, 'profile-classic')
  characterStatistics = this.createClientResourceRequest(wow.characterStatistics, 'profile-classic')
  connectedRealm = this.createClientResourceRequest(wow.connectedRealm, 'dynamic-classic')
  connectedRealmSearch = this.createClientResourceRequest(wow.connectedRealmSearch, 'dynamic-classic')
  creature = this.createClientResourceRequest(wow.creature, 'static-classic')
  creatureFamily = this.createClientResourceRequest(wow.creatureFamily, 'static-classic')
  creatureSearch = this.createClientResourceRequest(wow.creatureSearch, 'static-classic')
  creatureType = this.createClientResourceRequest(wow.creatureType, 'static-classic')
  guild = this.createClientResourceRequest(wow.guild, 'profile-classic')
  guildCrest = this.createClientResourceRequest(wow.guildCrest, 'static-classic')
  item = this.createClientResourceRequest(wow.item, 'static-classic')
  itemSearch = this.createClientResourceRequest(wow.itemSearch, 'static-classic')
  mediaSearch = this.createClientResourceRequest(wow.mediaSearch, 'static-classic')
  playableClass = this.createClientResourceRequest(wow.playableClass, 'static-classic')
  playableRace = this.createClientResourceRequest(wow.playableRace, 'static-classic')
  powerType = this.createClientResourceRequest(wow.powerType, 'static-classic')
  realm = this.createClientResourceRequest(wow.realm, 'dynamic-classic')
  realmSearch = this.createClientResourceRequest(wow.realmSearch, 'dynamic-classic')
  region = this.createClientResourceRequest(wow.region, 'dynamic-classic')
  token = this.createClientResourceRequest(wow.token, 'dynamic-classic')
}

export class WoWClassicEra extends Blizzard {
  accountCharacterProfile = this.createClientResourceRequest(wow.accountCharacterProfile, 'profile-classic1x')
  accountProfile = this.createClientResourceRequest(wow.accountProfile, 'profile-classic1x')
  auctionHouse = this.createClientResourceRequest(classic.auctionHouse, 'dynamic-classic')
  characterAchievements = this.createClientResourceRequest(wow.characterAchievements, 'profile-classic1x')
  characterAppearance = this.createClientResourceRequest(wow.characterAppearance, 'profile-classic1x')
  characterEquipment = this.createClientResourceRequest(wow.characterEquipment, 'profile-classic1x')
  characterHunterPets = this.createClientResourceRequest(wow.characterHunterPets, 'profile-classic1x')
  characterMedia = this.createClientResourceRequest(wow.characterMedia, 'profile-classic1x')
  characterPVP = this.createClientResourceRequest(wow.characterPVP, 'profile-classic1x')
  characterProfile = this.createClientResourceRequest(wow.characterProfile, 'profile-classic1x')
  characterStatistics = this.createClientResourceRequest(wow.characterStatistics, 'profile-classic1x')
  connectedRealm = this.createClientResourceRequest(wow.connectedRealm, 'dynamic-classic1x')
  connectedRealmSearch = this.createClientResourceRequest(wow.connectedRealmSearch, 'dynamic-classic1x')
  creature = this.createClientResourceRequest(wow.creature, 'static-classic1x')
  creatureFamily = this.createClientResourceRequest(wow.creatureFamily, 'static-classic1x')
  creatureSearch = this.createClientResourceRequest(wow.creatureSearch, 'static-classic1x')
  creatureType = this.createClientResourceRequest(wow.creatureType, 'static-classic1x')
  guild = this.createClientResourceRequest(wow.guild, 'profile-classic1x')
  guildCrest = this.createClientResourceRequest(wow.guildCrest, 'static-classic1x')
  item = this.createClientResourceRequest(wow.item, 'static-classic1x')
  itemSearch = this.createClientResourceRequest(wow.itemSearch, 'static-classic1x')
  mediaSearch = this.createClientResourceRequest(wow.mediaSearch, 'static-classic1x')
  playableClass = this.createClientResourceRequest(wow.playableClass, 'static-classic1x')
  playableRace = this.createClientResourceRequest(wow.playableRace, 'static-classic1x')
  powerType = this.createClientResourceRequest(wow.powerType, 'static-classic1x')
  realm = this.createClientResourceRequest(wow.realm, 'dynamic-classic1x')
  realmSearch = this.createClientResourceRequest(wow.realmSearch, 'dynamic-classic1x')
  region = this.createClientResourceRequest(wow.region, 'dynamic-classic1x')
  token = this.createClientResourceRequest(wow.token, 'dynamic-classic1x')
}

export type WoWClassicClient = WoWClassic
