import { Blizzard, BlizzardClient } from '../core'
import { ProtectedResourceOptions, ResourceResponse, ResourceOptions } from '../resources'
import * as wow from '../resources/wow'

export interface WoWClient extends BlizzardClient {
  accountCharacterProfile<T = any>(
    args: ProtectedResourceOptions<wow.AccountCharacterProfileOptions>,
  ): ResourceResponse<T>
  accountCollections<T = any>(args?: ProtectedResourceOptions<wow.AccountCollectionsOptions>): ResourceResponse<T>
  accountProfile<T = any>(args: ProtectedResourceOptions<wow.AccountProfileOptions>): ResourceResponse<T>
  achievement<T = any>(args?: ResourceOptions<wow.AchievementOptions>): ResourceResponse<T>
  achievementCategory<T = any>(args?: ResourceOptions<wow.AchievementCategoryOptions>): ResourceResponse<T>
  auctionHouse<T = any>(args: ResourceOptions<wow.AuctionHouseOptions>): ResourceResponse<T>
  azeriteEssence<T = any>(args?: ResourceOptions<wow.AzeriteEssenceOptions>): ResourceResponse<T>
  azeriteEssenceSearch<T = any>(args: ResourceOptions<wow.AzeriteEssenceSearchOptions>): ResourceResponse<T>
  characterAchievements<T = any>(args: ResourceOptions<wow.AccountCharacterAchievementsOptions>): ResourceResponse<T>
  characterAppearance<T = any>(args: ResourceOptions<wow.CharacterAppearanceOptions>): ResourceResponse<T>
  characterCollections<T = any>(args: ResourceOptions<wow.CharacterCollectionsOptions>): ResourceResponse<T>
  characterEncounters<T = any>(args: ResourceOptions<wow.CharacterEncountersOptions>): ResourceResponse<T>
  characterEquipment<T = any>(args: ResourceOptions<wow.CharacterEquipmentOptions>): ResourceResponse<T>
  characterHunterPets<T = any>(args: ResourceOptions<wow.CharacterHunterPetsOptions>): ResourceResponse<T>
  characterMedia<T = any>(args: ResourceOptions<wow.CharacterMediaOptions>): ResourceResponse<T>
  characterMythicKeystone<T = any>(args: ResourceOptions<wow.CharacterMythicKeystoneOptions>): ResourceResponse<T>
  characterProfessions<T = any>(args: ResourceOptions<wow.CharacterProfessionsOptions>): ResourceResponse<T>
  characterProfile<T = any>(args: ResourceOptions<wow.CharacterProfileOptions>): ResourceResponse<T>
  characterPVP<T = any>(args: ResourceOptions<wow.CharacterPVPOptions>): ResourceResponse<T>
  characterQuests<T = any>(args: ResourceOptions<wow.CharacterQuestsOptions>): ResourceResponse<T>
  characterReputations<T = any>(args: ResourceOptions<wow.CharacterReputationsOptions>): ResourceResponse<T>
  characterSoulbinds<T = any>(args: ResourceOptions<wow.CharacterSoulbindsOptions>): ResourceResponse<T>
  characterSpecializations<T = any>(args: ResourceOptions<wow.CharacterSpecializationsOptions>): ResourceResponse<T>
  characterStatistics<T = any>(args: ResourceOptions<wow.CharacterStatisticsOptions>): ResourceResponse<T>
  characterTitles<T = any>(args: ResourceOptions<wow.CharacterTitlesOptions>): ResourceResponse<T>
  conduit<T = any>(args?: ResourceOptions<wow.ConduitOptions>): ResourceResponse<T>
  connectedRealm<T = any>(args?: ResourceOptions<wow.ConnectedRealmOptions>): ResourceResponse<T>
  connectedRealmSearch<T = any>(args: ResourceOptions<wow.ConnectedRealmSearchOptions>): ResourceResponse<T>
  covenant<T = any>(args?: ResourceOptions<wow.CovenantOptions>): ResourceResponse<T>
  creature<T = any>(args: ResourceOptions<wow.CreatureOptions>): ResourceResponse<T>
  creatureFamily<T = any>(args?: ResourceOptions<wow.CreatureFamilyOptions>): ResourceResponse<T>
  creatureSearch<T = any>(args: ResourceOptions<wow.CreatureSearchOptions>): ResourceResponse<T>
  creatureType<T = any>(args?: ResourceOptions<wow.CreatureTypeOptions>): ResourceResponse<T>
  guild<T = any>(args: ResourceOptions<wow.GuildOptions>): ResourceResponse<T>
  guildCrest<T = any>(args?: ResourceOptions<wow.GuildCrestOptions>): ResourceResponse<T>
  item<T = any>(args: ResourceOptions<wow.ItemOptions>): ResourceResponse<T>
  itemSearch<T = any>(args: ResourceOptions<wow.ItemSearchOptions>): ResourceResponse<T>
  journal<T = any>(args: ResourceOptions<wow.JournalOptions>): ResourceResponse<T>
  mediaSearch<T = any>(args: ResourceOptions<wow.MediaSearchOptions>): ResourceResponse<T>
  modifiedCrafting<T = any>(args?: ResourceOptions<wow.ModifiedCraftingOptions>): ResourceResponse<T>
  mount<T = any>(args?: ResourceOptions<wow.MountOptions>): ResourceResponse<T>
  mountSearch<T = any>(args: ResourceOptions<wow.MountSearchOptions>): ResourceResponse<T>
  mythicKeystone<T = any>(args?: ResourceOptions<wow.MythicKeystoneOptions>): ResourceResponse<T>
  mythicKeystoneAffix<T = any>(args?: ResourceOptions<wow.MythicKeystoneAffixOptions>): ResourceResponse<T>
  mythicKeystoneLeaderboard<T = any>(args: ResourceOptions<wow.MythicKeystoneLeaderboardOptions>): ResourceResponse<T>
  mythicRaidLeaderboard<T = any>(args: ResourceOptions<wow.MythicRaidLeaderboardOptions>): ResourceResponse<T>
  pet<T = any>(args?: ResourceOptions<wow.PetOptions>): ResourceResponse<T>
  playableClass<T = any>(args?: ResourceOptions<wow.PlayableClassOptions>): ResourceResponse<T>
  playableRace<T = any>(args?: ResourceOptions<wow.PlayableRaceOptions>): ResourceResponse<T>
  playableSpecialization<T = any>(args?: ResourceOptions<wow.PlayableSpecializationOptions>): ResourceResponse<T>
  powerType<T = any>(args?: ResourceOptions<wow.PowerTypeOptions>): ResourceResponse<T>
  profession<T = any>(args?: ResourceOptions<wow.ProfessionOptions>): ResourceResponse<T>
  pvpSeason<T = any>(args?: ResourceOptions<wow.PVPSeasonOptions>): ResourceResponse<T>
  pvpTier<T = any>(args?: ResourceOptions<wow.PVPTierOptions>): ResourceResponse<T>
  quest<T = any>(args?: ResourceOptions<wow.QuestOptions>): ResourceResponse<T>
  realm<T = any>(args?: ResourceOptions<wow.RealmOptions>): ResourceResponse<T>
  realmSearch<T = any>(args: ResourceOptions<wow.RealmSearchOptions>): ResourceResponse<T>
  recipe<T = any>(args: ResourceOptions<wow.RecipeOptions>): ResourceResponse<T>
  region<T = any>(args?: ResourceOptions<wow.RegionOptions>): ResourceResponse<T>
  reputation<T = any>(args: ResourceOptions<wow.ReputationOptions>): ResourceResponse<T>
  soulbind<T = any>(args?: ResourceOptions<wow.SoulbindOptions>): ResourceResponse<T>
  spell<T = any>(args: ResourceOptions<wow.SpellOptions>): ResourceResponse<T>
  spellSearch<T = any>(args: ResourceOptions<wow.SpellSearchOptions>): ResourceResponse<T>
  talent<T = any>(args?: ResourceOptions<wow.TalentOptions>): ResourceResponse<T>
  techTalent<T = any>(args?: ResourceOptions<wow.TechTalentOptions>): ResourceResponse<T>
  title<T = any>(args?: ResourceOptions<wow.TitleOptions>): ResourceResponse<T>
  token<T = any>(args?: ResourceOptions<wow.TokenOptions>): ResourceResponse<T>
}

export class WoW extends Blizzard implements WoWClient {
  accountCharacterProfile = this.createClientResourceRequest(wow.accountCharacterProfile.bind(this, 'profile'))
  accountCollections = this.createClientResourceRequest(wow.accountCollections.bind(this, 'profile'))
  accountProfile = this.createClientResourceRequest(wow.accountProfile.bind(this, 'profile'))
  achievement = this.createClientResourceRequest(wow.achievement.bind(this, 'static'))
  achievementCategory = this.createClientResourceRequest(wow.achievementCategory.bind(this, 'static'))
  auctionHouse = this.createClientResourceRequest(wow.auctionHouse.bind(this, 'dynamic'))
  azeriteEssence = this.createClientResourceRequest(wow.azeriteEssence.bind(this, 'static'))
  azeriteEssenceSearch = this.createClientResourceRequest(wow.azeriteEssenceSearch.bind(this, 'static'))
  characterAchievements = this.createClientResourceRequest(wow.characterAchievements.bind(this, 'profile'))
  characterAppearance = this.createClientResourceRequest(wow.characterAppearance.bind(this, 'profile'))
  characterCollections = this.createClientResourceRequest(wow.characterCollections.bind(this, 'profile'))
  characterEncounters = this.createClientResourceRequest(wow.characterEncounters.bind(this, 'profile'))
  characterEquipment = this.createClientResourceRequest(wow.characterEquipment.bind(this, 'profile'))
  characterHunterPets = this.createClientResourceRequest(wow.characterHunterPets.bind(this, 'profile'))
  characterMedia = this.createClientResourceRequest(wow.characterMedia.bind(this, 'profile'))
  characterMythicKeystone = this.createClientResourceRequest(wow.characterMythicKeystone.bind(this, 'profile'))
  characterProfessions = this.createClientResourceRequest(wow.characterProfessions.bind(this, 'profile'))
  characterProfile = this.createClientResourceRequest(wow.characterProfile.bind(this, 'profile'))
  characterPVP = this.createClientResourceRequest(wow.characterPVP.bind(this, 'profile'))
  characterQuests = this.createClientResourceRequest(wow.characterQuests.bind(this, 'profile'))
  characterReputations = this.createClientResourceRequest(wow.characterReputations.bind(this, 'profile'))
  characterSoulbinds = this.createClientResourceRequest(wow.characterSoulbinds.bind(this, 'profile'))
  characterSpecializations = this.createClientResourceRequest(wow.characterSpecializations.bind(this, 'profile'))
  characterStatistics = this.createClientResourceRequest(wow.characterStatistics.bind(this, 'profile'))
  characterTitles = this.createClientResourceRequest(wow.characterTitles.bind(this, 'profile'))
  conduit = this.createClientResourceRequest(wow.conduit.bind(this, 'static'))
  connectedRealm = this.createClientResourceRequest(wow.connectedRealm.bind(this, 'dynamic'))
  connectedRealmSearch = this.createClientResourceRequest(wow.connectedRealmSearch.bind(this, 'dynamic'))
  covenant = this.createClientResourceRequest(wow.covenant.bind(this, 'static'))
  creature = this.createClientResourceRequest(wow.creature.bind(this, 'static'))
  creatureFamily = this.createClientResourceRequest(wow.creatureFamily.bind(this, 'static'))
  creatureSearch = this.createClientResourceRequest(wow.creatureSearch.bind(this, 'static'))
  creatureType = this.createClientResourceRequest(wow.creatureType.bind(this, 'static'))
  guild = this.createClientResourceRequest(wow.guild.bind(this, 'profile'))
  guildCrest = this.createClientResourceRequest(wow.guildCrest.bind(this, 'static'))
  item = this.createClientResourceRequest(wow.item.bind(this, 'static'))
  itemSearch = this.createClientResourceRequest(wow.itemSearch.bind(this, 'static'))
  journal = this.createClientResourceRequest(wow.journal.bind(this, 'static'))
  mediaSearch = this.createClientResourceRequest(wow.mediaSearch.bind(this, 'static'))
  modifiedCrafting = this.createClientResourceRequest(wow.modifiedCrafting.bind(this, 'static'))
  mount = this.createClientResourceRequest(wow.mount.bind(this, 'static'))
  mountSearch = this.createClientResourceRequest(wow.mountSearch.bind(this, 'static'))
  mythicKeystone = this.createClientResourceRequest(wow.mythicKeystone.bind(this, 'dynamic'))
  mythicKeystoneAffix = this.createClientResourceRequest(wow.mythicKeystoneAffix.bind(this, 'static'))
  mythicKeystoneLeaderboard = this.createClientResourceRequest(wow.mythicKeystoneLeaderboard.bind(this, 'dynamic'))
  mythicRaidLeaderboard = this.createClientResourceRequest(wow.mythicRaidLeaderboard.bind(this, 'dynamic'))
  pet = this.createClientResourceRequest(wow.pet.bind(this, 'static'))
  playableClass = this.createClientResourceRequest(wow.playableClass.bind(this, 'static'))
  playableRace = this.createClientResourceRequest(wow.playableRace.bind(this, 'static'))
  playableSpecialization = this.createClientResourceRequest(wow.playableSpecialization.bind(this, 'static'))
  powerType = this.createClientResourceRequest(wow.powerType.bind(this, 'static'))
  profession = this.createClientResourceRequest(wow.profession.bind(this, 'static'))
  pvpSeason = this.createClientResourceRequest(wow.pvpSeason.bind(this, 'dynamic'))
  pvpTier = this.createClientResourceRequest(wow.pvpTier.bind(this, 'static'))
  quest = this.createClientResourceRequest(wow.quest.bind(this, 'static'))
  realm = this.createClientResourceRequest(wow.realm.bind(this, 'dynamic'))
  realmSearch = this.createClientResourceRequest(wow.realmSearch.bind(this, 'dynamic'))
  recipe = this.createClientResourceRequest(wow.recipe.bind(this, 'static'))
  region = this.createClientResourceRequest(wow.region.bind(this, 'dynamic'))
  reputation = this.createClientResourceRequest(wow.reputation.bind(this, 'static'))
  soulbind = this.createClientResourceRequest(wow.soulbind.bind(this, 'static'))
  spell = this.createClientResourceRequest(wow.spell.bind(this, 'static'))
  spellSearch = this.createClientResourceRequest(wow.spellSearch.bind(this, 'static'))
  talent = this.createClientResourceRequest(wow.talent.bind(this, 'static'))
  techTalent = this.createClientResourceRequest(wow.techTalent.bind(this, 'static'))
  title = this.createClientResourceRequest(wow.title.bind(this, 'static'))
  token = this.createClientResourceRequest(wow.token.bind(this, 'dynamic'))
}
